### ISSUE TITLE
Broken link in article

### ISSUE THREAD

**Issue by LouisCAD** [wakingrufus/website#2]
https://codetown.com/group/kotlin/forum/topics/kotlin-thursdays-static-web-with-kotlin-dsls-with-john-burns

At the end of the article, there's this:
> my [Website](https://neocities.org/wakingrufus)

The link is broke, because it uses path instead of subdomain.

The correct url as you surely know, is this one: https://wakingrufus.neocities.org/

**Comment by LouisCAD** [comment]
There's alos this 404 link: https://proandroiddev.com/auto-generate-kotlin-dsl-f63342434154s?gi=db371681391d

**Comment by LouisCAD** [comment]
And "Neocities" that links to neocites.org (where is the missing "i"?)

**Comment by wakingrufus** [comment]
fixes pushed to the site. Thanks for the report @LouisCAD
